### ISSUE TITLE
Update to support Socket v4

### ISSUE THREAD

**Issue by m1ga** [tidev/titanium-socketio#168]
Update the Android and iOS module to support Socket Server v4

Android version is here already: https://github.com/tidev/titanium-socketio/pull/164
(used by some Slack members already)

Current nodejs workaround is:
```js
const io = new Server(httpServer, {
  allowEIO3: true // false by default
});
```

**Comment by hansemannn** [comment]
Android already supported (thanks @m1ga), iOS can be tracked here: #174
